### ISSUE TITLE
Does pandokia use stash.py in stsci.tools?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pandokia#13]
xref spacetelescope/stsci.tools#74

**Comment by jhunkeler** [comment]
@pllim not that I've seen. The only reference to `stsci.tools` is here: https://github.com/spacetelescope/pandokia/blob/303c75b4af2eaca79f178dd71693f81b72036b93/pandokia/helpers/pytest_plugin.py#L212-L223

Apparently it will attempt to use `stsci.tools.tester` if it exists...

**Comment by pllim** [comment]
Thanks!
