### ISSUE TITLE
Astropy 3.0 will not support Python 2 anymore

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pandokia#5]
I heard this is a big problem for pandokia, as it still relies on Python 2.

**Comment by bernie-simon** [comment]
I modified the code in Pandokia to run under Python 3 as part of the Python 2 to 3 migration. I can't guarantee it works. Ironically, Pandokia lacks a complete set of tests. But has anyone tried running Pandokia under Python 3? What problems did you find?

**Comment by pllim** [comment]
@jhunkeler also has a version that works in Python 3. However, even if pandokia itself works in Python 3, the actual tests might not, and we might be talking about a lot of tests spanning the history of HST.

**Comment by pllim** [comment]
We need to start thinking about how `dev` testing is going to work when Astropy dev removes Python 2 support completely in 2 weeks.
