### ISSUE TITLE
BROKEN: "Mark Valuable" 

### ISSUE THREAD

**Issue by vglaidler** [spacetelescope/pandokia#57]
The key functionality "Mark valuable" is broken. Discovered 4/25/2019 in operational install at https://glitch.etc.stsci.edu/pandokia.cgi?query=action&qid=21648&valuable_qid=1

Traceback very weirdly points here: https://github.com/spacetelescope/pandokia/blob/master/pandokia/pcgi_action.py#L147

Last modified at 81f4946dbc779766c0c8a08002f98939f660d007

Judging from the surrounding changes, this looks like a straight-up typo.

@jhunkeler, looks like you made those changes - can you please confirm that this was not intentional & it should be form.getvalue() as elsewhere in the changeset?

**Comment by jhunkeler** [comment]
I probably used `sed` to perform those replacements and that line got missed. Ack!

**Comment by vglaidler** [comment]
Thanks @jhunkeler , seems like it should be a pretty straightforward fix then.
