### ISSUE TITLE
XML tests: fitsdiff gives TypeError "a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pandokia#9]
For example: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=115404474

```
Traceback (most recent call last):
  File ".../envs/dev/bin/fitsdiff", line 11, in <module>
    sys.exit(main())
  File ".../envs/dev/lib/python3.5/site-packages/astropy/io/fits/scripts/fitsdiff.py", line 316, in main
    diff.report(fileobj=out_file)
  File ".../envs/dev/lib/python3.5/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File ".../envs/dev/lib/python3.5/site-packages/astropy/io/fits/diff.py", line 188, in report
    self._report()
  File ".../astropy/io/fits/diff.py", line 363, in _report
    self._fileobj.write(u('\n'))
TypeError: a bytes-like object is required, not 'str'
! fits comparison FAILED for ref/calstis_lev3_FUV_x2d.fits and out/calstis_lev3_FUV_x2d.fits
```

All the tests with this failure used XML test script. I did not see such error from Python test script.

**Comment by bernie-simon** [comment]
I had a similar problem with json files. The problem was resolved by updating the version of the json library. It didn't work with Python 3.

**Comment by pllim** [comment]
Why do you mean updating json library? I thought `json` comes with Python (i.e., it is a built in module)?

**Comment by bernie-simon** [comment]
The json library is used by asdf. And when I pointed out the problem, it was updated. I don't think it's a Python built in module.

**Comment by pllim** [comment]
So, you don't mean this one -- https://docs.python.org/3/library/json.html ?

**Comment by bernie-simon** [comment]
It's 

./anaconda3/pkgs/python-3.5.3-1/lib/python3.5/json

and

./anaconda3/pkgs/python-3.6.0-0/lib/python3.6/json

on my system.

**Comment by drdavella** [comment]
There is a difference in the `json` module that Python provides between 3.5 and 3.6. Here's the ASDF issue that Bernie is talking about: https://github.com/spacetelescope/asdf/issues/314. See the linked PR for the workaround.

**Comment by pllim** [comment]
Thanks for the suggested fix in spacetelescope/asdf#317 . Unfortunately, I don't even know where to put that in `pandokia`...

**Comment by pllim** [comment]
@drdavella , are you saying that this error will magically go away if we upgrade to Python 3.6 (which we should anyway)?

**Comment by drdavella** [comment]
I would guess it would but this looks like a bug in `fitsdiff` right?

**Comment by pllim** [comment]
No. It only appears when XML test scripts are used. Python scripts are okay. So my hunch is that XML files are not ingested properly in pandokia for Python 3.5.

**Comment by drdavella** [comment]
Sorry to be dense but why is the traceback from within astropy?

**Comment by pllim** [comment]
It is a mystery. If it is indeed astropy, *all* the comparisons would have failed.

**Comment by stscirij** [comment]
It appears to be an error in fitsdiff when writing to an output file (-o option).

e.g. fitsdiff file1.fits file2.fits

works OK, but 

fitsdiff file1.fits file2.fits -o diff.txt

gives the TypeError.

**Comment by stscirij** [comment]
You get this type of error when you try to write strings to a file that has been opened with mode 'wb', yet it appears to have been opened with mode 'w', which defaults to text.  So I'm at a loss as to how to fix it - anyone?

**Comment by drdavella** [comment]
Do you know what kind of file object is being written to? We've seen a problem like this (alluded to above) with JSON file objects where there was a difference between Py3.5 and 3.6 in the types of objects that were accepted. This seems like it may be something similar.

**Comment by pllim** [comment]
> a file that has been opened with mode 'wb', yet it appears to have been opened with mode 'w'

Not sure if I understand. How is this even possible?

**Comment by pllim** [comment]
I just tried `fitsdiff jbbglbm6q_flt.fits jbbgmauiq_flt.fits -o diff.txt` in both my Python 3.5.4 and 3.6.3 environments and got no error.

**Comment by drdavella** [comment]
Are the files actually different? I get it in a Py 3.6 environment with just two random FITS files I have sitting around.

**Comment by pllim** [comment]
I tried with both different files (with real diff) and same file on Python 3.6. Still no error. What astropy version are you using? Maybe this is a bug that has been fixed in dev.

**Comment by drdavella** [comment]
I saw the error on 2.0.2 but not on the dev branch, so maybe you're right.

**Comment by pllim** [comment]
I wonder if the fix was cherry picked into 2.x branch for 2.0.3... If it is not much trouble, can you try this again with the current 2.x branch?

**Comment by pllim** [comment]
Hmm... Then we should definitely open an issue on astropy about this for 2.x. A `git bisect` is probably in order to hunt down the fix and see which piece of code needs backporting.

**Comment by pllim** [comment]
Although... this still does not explain why STIS tests are failing with the `fitsdiff` error in the "dev" environment, because the "dev" environment should be using the latest astropy dev, which would have the fix for this. So, the problem we found for Astropy is not the same problem that is causing this?

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=117063082

**Comment by drdavella** [comment]
That is strange. Is there any way to get these scripts to report the version of astropy they are using?

**Comment by pllim** [comment]
@jhunkeler , from https://ssb.stsci.edu/steuermann/s21.cgi?action=log&name=conda_tests_py3_2017-10-11-10:30:02/nott:conda_testing3/dev_tests , it appears that "dev" tests are using `astropy 2.0.2`, not `astropy 3.0.devxxxx`. Is this supposed to happen?

**Comment by drdavella** [comment]
I just opened a PR for this in astropy: https://github.com/astropy/astropy/pull/6726

**Comment by jhunkeler** [comment]
@pllim Nope, not supposed to happen. The latest conda resolver is ignoring the package. I'm on my way out of town - can't it fix yet. We'll need to pin conda to an older release (4.3.25) for the time being. Continuum rolled out a new packaging convention starting with 4.3.27.

**Comment by stscirij** [comment]
This is fixed in astropy master and Matt has fixed the regression test environment so that it runs the version of fitsdiff from astropy dev when doing regtest-like tests (like the stis tests).  This should clear up the errors.

**Comment by pllim** [comment]
Yay, they passed today! Thank you, all! 🎉
